apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gitops-demo
  namespace: argocd
spec:
  writeBackConfig:
    method: git:secret:argocd-image-updater/git-creds
    gitConfig:
      branch: main
      writeBackTarget: kustomization
  applicationRefs:
    - namePattern: gitops-demo
      images:
        - alias: app
          imageName: ghcr.io/rmiravalles/argocd-gitops-demo:latest
          commonUpdateSettings:
            updateStrategy: digest