apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app-gitops-demo
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/rmiravalles/argocd-gitops-demo
    newTag: latest